edited: README - stacks, startup
julycrystal/shopify-react-storefront pull request #6
Opened 2023-05-05 09:28 UTC by julycrystal

Edited readme for better understanding of project.
Please have a look at.

2023-05-05 15:10 UTC, oddcommits requested changes

2023-05-05 15:10 UTC, oddcommits commented on README.md
> +# Shopify Storefront With Fancy Styles
?

2023-05-05 23:11 UTC, julycrystal commented on README.md
> +# Shopify Storefront With Fancy Styles
Fixed those issues.

2023-05-05 23:38 UTC, oddcommits requested changes

2023-05-05 23:38 UTC, oddcommits commented on README.md
> +## Stacks used
not `Stacks` but `Stack`. or can be `Technologies`

2023-05-06 01:45 UTC, julycrystal commented on README.md
> +## Stacks used
Fixed to `Technologies`

2023-05-06 02:09 UTC, oddcommits approved these changes

2023-05-06 02:10 UTC, merged